/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { HealthChartContract } from "./HealthChart";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "HealthChart"): HealthChartContract;
    }
  }
}

export { HealthChartContract, HealthChartInstance } from "./HealthChart";
